repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        # Usa baseline versionado; sรณ acusa segredos novos
        args: ["--baseline", ".secrets.baseline"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        files: '^(src|tests|scripts|\.github)/'
      - id: check-merge-conflict
        files: '^(src|tests|scripts|\.github)/'
      - id: end-of-file-fixer
        files: '^(src|tests|scripts|\.github)/'
      - id: trailing-whitespace
        files: '^(src|tests|scripts|\.github)/'
