services:
  bot:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env
    environment:
      - PYTHONPATH=/app
    command: ["bash", "-lc", "docker/start.sh"]
    restart: always
