execution:
  mode: maker_first
  partial_at_r: 0.8
  sl_atr_mult: 0.9
  tp_atr_mult: 1.8
  trailing_after_r: 1.0
  trailing_atr_mult: 0.8
filters:
  adx_trend_min: 18
  atrq_high: 0.85
  atrq_low: 0.25
  use_atr_quantile: true
history_days: 60
slippage_fees:
  maker_bps: 0.02
  slip_bps_base: 0.04
  slip_bps_perc_of_atr: 0.12
  taker_bps: 0.05
symbols:
- BTCUSDT
timeframe: 5m
