symbols: ["BTCUSDT"]
timeframe: "5m"
history_days: 60
filters:
  adx_trend_min: 999   # força regime range (MR)
  use_atr_quantile: true
  atrq_low: 0.25
  atrq_high: 0.80
execution:
  mode: "taker"
  tp_atr_mult: 1.6
  sl_atr_mult: 1.0
  partial_at_r: 0.8
  trailing_after_r: 1.0
  trailing_atr_mult: 0.8
slippage_fees:
  maker_bps: 0.020
  taker_bps: 0.055
  slip_bps_base: 0.05
  slip_bps_perc_of_atr: 0.12
