symbols: ["BTCUSDT"]
timeframe: "5m"
history_days: 60
filters:
  adx_trend_min: 16
  use_atr_quantile: true
  atrq_low: 0.25
  atrq_high: 0.85
execution:
  mode: "maker_first"
  tp_atr_mult: 2.0
  sl_atr_mult: 1.0
  partial_at_r: 0.8
  trailing_after_r: 1.0
  trailing_atr_mult: 0.8
