name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest flake8 pre-commit detect-secrets

      - name: Pre-commit (enforce hooks)
        run: |
          pre-commit run --all-files

      - name: Lint (flake8)
        run: |
          flake8

      - name: Run tests (se houver pasta tests/)
        run: |
          if [ -d tests ]; then pytest -q; else echo "Sem pasta tests/ — ok"; fi
