name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Lint (flake8) — não falha o job se apontar avisos
      run: |
        pip install flake8
        flake8 || true

    - name: Run tests (se houver pasta tests/)
      run: |
        if [ -d tests ]; then pytest -q || true; else echo "Sem pasta tests/ — ok"; fi
